/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 assets2.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/assets2.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002_Material003_0.geometry} material={materials['Material.003']} position={[0, 2.516, 0]} rotation={[-1.589, 0, 0]} />
      <mesh geometry={nodes.Cone002_Material007_0.geometry} material={materials['Material.007']} position={[0, 2.097, 0]} rotation={[-1.589, 0, 0]} />
      <mesh geometry={nodes.Plane009_Material008_0.geometry} material={materials['Material.008']} position={[0, 3.786, 0]} rotation={[-1.589, 0, 0]} />
      <mesh geometry={nodes.Icosphere018_Material002_0.geometry} material={materials['Material.002']} position={[0, 3.786, 0]} rotation={[-1.589, 0, 0]} />
      <mesh geometry={nodes.Circle001_Material015_0.geometry} material={materials['Material.015']} position={[0, 3.124, 0]} rotation={[-1.589, 0, 0]} scale={[1, 1, 1.74]} />
      <mesh geometry={nodes.Plane015_Material023_0.geometry} material={materials['Material.023']} position={[0, 2.939, 0]} rotation={[-1.589, 0, 0]} />
      <mesh geometry={nodes.Icosphere006_Material028_0.geometry} material={materials['Material.028']} position={[0, 1.003, 0]} rotation={[-1.589, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/assets2.glb')
