/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.3 tree1.glb
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/tree1.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Plane002_Material003_0.geometry} material={materials['Material.003']} position={[-282.244, 249.559, 805.287]} rotation={[-Math.PI / 2, 0, -0.755]} scale={100} />
    </group>
  )
}

useGLTF.preload('/tree1.glb')
