/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 popup.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/popup.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.body.geometry} material={materials.Material} position={[0.004, 1.908, 0.065]} scale={[1.957, -1.036, 0.135]} />
      <mesh geometry={nodes.picture.geometry} material={nodes.picture.material} position={[0.013, 1.92, 0.21]} rotation={[1.57, 0, 0]} scale={[1.755, 0.528, 0.911]} />
    </group>
  )
}

useGLTF.preload('/popup.glb')
