/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 treepack.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/treepack.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.tree_1.geometry} material={materials['Material.003']} position={[-0.019, 0.554, 0]} rotation={[-1.674, 0.004, 0.424]} scale={0.2} />
      <mesh geometry={nodes.tree_2.geometry} material={materials['Material.009']} position={[-0.223, 0.459, 0]} rotation={[-1.559, 0, 0]} scale={0.2} />
      <mesh geometry={nodes.tree_0.geometry} material={materials['Material.005']} position={[0.01, 0.503, 0]} rotation={[-1.555, 0, 0]} scale={0.2} />
    </group>
  )
}

useGLTF.preload('/treepack.glb')
